---

- name: check | infrastructure pods are up
  shell: "oc --config=../kubeconfig get pods -n {{item}}"
  register: oc_get_pods
  changed_when: 1==2
  failed_when: "'Terminated' in oc_get_pods.stdout or 'ErrImagePull' in oc_get_pods.stdout or 'Failed' in oc_get_pods.stdout or 'Crash' in oc_get_pods.stdout"
  with_items:
    - default
    - kube-system
    - openshift-console
    - openshift-web-console
    - openshift-sdn

- name: check | all pods in all projects are running
  shell: "oc --config=../kubeconfig get pods --all-namespaces"
  register: oc_get_pods
  changed_when: 1==2
  failed_when: "'Terminated' in oc_get_pods.stdout or 'Err' in oc_get_pods.stdout or 'Failed' in oc_get_pods.stdout or 'Crash' in oc_get_pods.stdout"

- name: check | node status
  shell: "oc --config=../kubeconfig get nodes"
  register: oc_get_nodes
  changed_when: 1==2
  failed_when: "'NotReady' in oc_get_nodes.stdout"

- name: check | router
  shell: "oc --config=../kubeconfig -n default get deploymentconfigs/router"
  register: router_health
  changed_when: 1==2
  failed_when: "'router' not in router_health.stdout"

- name: check | etcd
  shell: "source /etc/etcd/etcd.conf && etcdctl2 --cert-file=$ETCD_PEER_CERT_FILE --key-file=$ETCD_PEER_KEY_FILE --ca-file=/etc/etcd/ca.crt --endpoints=$ETCD_LISTEN_CLIENT_URLS cluster-health"
  register: etcd_health
  changed_when: 1==2
  failed_when: "'cluster is healthy' not in etcd_health.stdout"
  delegate_to: "{{groups['masters'] | first}}"
  when: etcdSkip is not defined

- name: check | console
  uri:
    url: "https://{{openshift_console_api}}"
    validate_certs: no
  register: console_check
  until: "'OK' in console_check.msg"
  retries: 3
  delay: 2

