apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: {{testproject}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{localregistry}}
        ports:
        - name: web
          containerPort: 80
        volumeMounts:
        - mountPath: /var/log/nginx
          name: log
      volumes:
      - name: log
        emptyDir: {}
      imagePullPolicy: Always  
  triggers:
  - type: ConfigChange
  strategy:
    type: Rolling
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0
