---

- name: Create a project
  openshift_raw:
    api_version: v1
    kind: Project
    name: "{{testproject}}"
    kubeconfig: "../kubeconfig"
    state: present

- name: prepare nginx yaml
  template:
    src: nginx.yaml
    dest: roles/create_project/files/nginx.yaml

- name: prepare nginx pvc yaml
  template:
    src: nginxpvc.yaml
    dest: roles/create_project/files/nginxpvc.yaml

- name: prepare route yaml
  template:
    src: nginxroute.yaml
    dest: roles/create_project/files/nginxroute.yaml

- name: prepare service yaml
  template:
    src: nginxsvc.yaml
    dest: roles/create_project/files/nginxsvc.yaml

- name: deploy application | create nginx pvc
  openshift_raw:
    src: roles/create_project/files/nginxpvc.yaml
    state: present
    kubeconfig: "../kubeconfig"

- name: deploy application | deploy nginx deploymentconfig
  openshift_raw:
    src: roles/create_project/files/nginx.yaml
    state: present
    kubeconfig: "../kubeconfig"

- name: deploy application | create nginx service
  openshift_raw:
    src: roles/create_project/files/nginxsvc.yaml
    state: present
    kubeconfig: "../kubeconfig"

- name: deploy application | create route for nginx
  openshift_raw:
    src: roles/create_project/files/nginxroute.yaml
    state: present
    kubeconfig: "../kubeconfig"

- name: check | pods are up
  shell: "oc get pods -n {{testproject}} |grep -i nginx|grep -i Running"
  register: oc_get_pods
  until: "'Running' in oc_get_pods.stdout and 'deploy' not in oc_get_pods.stdout"
  retries: 60
  delay: 2
  delegate_to: "{{groups['masters'] | first}}"

- name: check | app answers via router
  uri:
    url: http://nginx-{{testproject}}.{{ocpappsdomain}}
    status_code: 403
  register: uri_check
  until: "'403' in uri_check.msg"
  retries: 20
  delay: 2

- name: Delete a project
  openshift_raw:
    api_version: v1
    kind: Project
    name: "{{testproject}}"
    kubeconfig: "../kubeconfig"
    state: absent
